/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MuscleGroup = IDL.Variant({
  'abs' : IDL.Null,
  'traps' : IDL.Null,
  'triceps' : IDL.Null,
  'shoulders' : IDL.Null,
  'back' : IDL.Null,
  'chest' : IDL.Null,
  'lats' : IDL.Null,
  'neck' : IDL.Null,
  'hamstrings' : IDL.Null,
  'quadriceps' : IDL.Null,
  'glutes' : IDL.Null,
  'calves' : IDL.Null,
  'forearms' : IDL.Null,
  'biceps' : IDL.Null,
});
export const Time = IDL.Int;
export const WorkoutLog = IDL.Record({
  'isBodyWeight' : IDL.Bool,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'weightKg' : IDL.Float64,
  'timestamp' : Time,
  'exerciseName' : IDL.Text,
  'muscleGroup' : MuscleGroup,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Goal = IDL.Variant({
  'recomposition' : IDL.Null,
  'buildMaxMuscle' : IDL.Null,
  'buildLeanMuscle' : IDL.Null,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'bodyFat' : IDL.Float64,
  'heightCm' : IDL.Float64,
  'goal' : Goal,
  'weightKg' : IDL.Float64,
  'gender' : Gender,
});
export const UserProteinRequirements = IDL.Record({
  'inCalorieMaintenance' : IDL.Float64,
  'total' : IDL.Float64,
  'minimum' : IDL.Float64,
  'onHighTrainingDays' : IDL.Float64,
  'inCalorieSurplus' : IDL.Float64,
  'inCalorieDeficit' : IDL.Float64,
  'optimal' : IDL.Float64,
});
export const InjuryLog = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'isResolved' : IDL.Bool,
  'muscleGroup' : MuscleGroup,
  'dateOfInjury' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInjuryLog' : IDL.Func([MuscleGroup, Time, IDL.Text], [IDL.Nat], []),
  'addWorkoutLog' : IDL.Func([WorkoutLog], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCallerWorkoutLogs' : IDL.Func([], [], []),
  'deleteInjuryLog' : IDL.Func([IDL.Nat], [], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllWorkoutLogsForCaller' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyProteinRequirementsForCaller' : IDL.Func(
      [],
      [UserProteinRequirements],
      ['query'],
    ),
  'getInjuryLogsForCaller' : IDL.Func([], [IDL.Vec(InjuryLog)], ['query']),
  'getLeanMassForCaller' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getOptimalProteinRangeForCaller' : IDL.Func(
      [],
      [IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resolveInjuryLog' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MuscleGroup = IDL.Variant({
    'abs' : IDL.Null,
    'traps' : IDL.Null,
    'triceps' : IDL.Null,
    'shoulders' : IDL.Null,
    'back' : IDL.Null,
    'chest' : IDL.Null,
    'lats' : IDL.Null,
    'neck' : IDL.Null,
    'hamstrings' : IDL.Null,
    'quadriceps' : IDL.Null,
    'glutes' : IDL.Null,
    'calves' : IDL.Null,
    'forearms' : IDL.Null,
    'biceps' : IDL.Null,
  });
  const Time = IDL.Int;
  const WorkoutLog = IDL.Record({
    'isBodyWeight' : IDL.Bool,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'weightKg' : IDL.Float64,
    'timestamp' : Time,
    'exerciseName' : IDL.Text,
    'muscleGroup' : MuscleGroup,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'recomposition' : IDL.Null,
    'buildMaxMuscle' : IDL.Null,
    'buildLeanMuscle' : IDL.Null,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'bodyFat' : IDL.Float64,
    'heightCm' : IDL.Float64,
    'goal' : Goal,
    'weightKg' : IDL.Float64,
    'gender' : Gender,
  });
  const UserProteinRequirements = IDL.Record({
    'inCalorieMaintenance' : IDL.Float64,
    'total' : IDL.Float64,
    'minimum' : IDL.Float64,
    'onHighTrainingDays' : IDL.Float64,
    'inCalorieSurplus' : IDL.Float64,
    'inCalorieDeficit' : IDL.Float64,
    'optimal' : IDL.Float64,
  });
  const InjuryLog = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'isResolved' : IDL.Bool,
    'muscleGroup' : MuscleGroup,
    'dateOfInjury' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInjuryLog' : IDL.Func([MuscleGroup, Time, IDL.Text], [IDL.Nat], []),
    'addWorkoutLog' : IDL.Func([WorkoutLog], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCallerWorkoutLogs' : IDL.Func([], [], []),
    'deleteInjuryLog' : IDL.Func([IDL.Nat], [], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllWorkoutLogsForCaller' : IDL.Func(
        [],
        [IDL.Vec(WorkoutLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyProteinRequirementsForCaller' : IDL.Func(
        [],
        [UserProteinRequirements],
        ['query'],
      ),
    'getInjuryLogsForCaller' : IDL.Func([], [IDL.Vec(InjuryLog)], ['query']),
    'getLeanMassForCaller' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getOptimalProteinRangeForCaller' : IDL.Func(
        [],
        [IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resolveInjuryLog' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };