/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'female' : null } |
  { 'male' : null };
export type Goal = { 'recomposition' : null } |
  { 'buildMaxMuscle' : null } |
  { 'buildLeanMuscle' : null };
export interface InjuryLog {
  'id' : bigint,
  'description' : string,
  'isResolved' : boolean,
  'muscleGroup' : MuscleGroup,
  'dateOfInjury' : Time,
}
export type MuscleGroup = { 'abs' : null } |
  { 'traps' : null } |
  { 'triceps' : null } |
  { 'shoulders' : null } |
  { 'back' : null } |
  { 'chest' : null } |
  { 'lats' : null } |
  { 'neck' : null } |
  { 'hamstrings' : null } |
  { 'quadriceps' : null } |
  { 'glutes' : null } |
  { 'calves' : null } |
  { 'forearms' : null } |
  { 'biceps' : null };
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'bodyFat' : number,
  'heightCm' : number,
  'goal' : Goal,
  'weightKg' : number,
  'gender' : Gender,
}
export interface UserProteinRequirements {
  'inCalorieMaintenance' : number,
  'total' : number,
  'minimum' : number,
  'onHighTrainingDays' : number,
  'inCalorieSurplus' : number,
  'inCalorieDeficit' : number,
  'optimal' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutLog {
  'isBodyWeight' : boolean,
  'reps' : bigint,
  'sets' : bigint,
  'weightKg' : number,
  'timestamp' : Time,
  'exerciseName' : string,
  'muscleGroup' : MuscleGroup,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInjuryLog' : ActorMethod<[MuscleGroup, Time, string], bigint>,
  'addWorkoutLog' : ActorMethod<[WorkoutLog], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCallerWorkoutLogs' : ActorMethod<[], undefined>,
  'deleteInjuryLog' : ActorMethod<[bigint], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllWorkoutLogsForCaller' : ActorMethod<[], Array<WorkoutLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyProteinRequirementsForCaller' : ActorMethod<
    [],
    UserProteinRequirements
  >,
  'getInjuryLogsForCaller' : ActorMethod<[], Array<InjuryLog>>,
  'getLeanMassForCaller' : ActorMethod<[], [] | [number]>,
  'getOptimalProteinRangeForCaller' : ActorMethod<[], [] | [[number, number]]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resolveInjuryLog' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];