/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InjuryLog {
    id: bigint;
    description: string;
    isResolved: boolean;
    muscleGroup: MuscleGroup;
    dateOfInjury: Time;
}
export interface UserProteinRequirements {
    inCalorieMaintenance: number;
    total: number;
    minimum: number;
    onHighTrainingDays: number;
    inCalorieSurplus: number;
    inCalorieDeficit: number;
    optimal: number;
}
export interface WorkoutLog {
    isBodyWeight: boolean;
    reps: bigint;
    sets: bigint;
    weightKg: number;
    timestamp: Time;
    exerciseName: string;
    muscleGroup: MuscleGroup;
}
export type Time = bigint;
export interface UserProfile {
    age: bigint;
    bodyFat: number;
    heightCm: number;
    goal: Goal;
    weightKg: number;
    gender: Gender;
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum Goal {
    recomposition = "recomposition",
    buildMaxMuscle = "buildMaxMuscle",
    buildLeanMuscle = "buildLeanMuscle"
}
export enum MuscleGroup {
    abs = "abs",
    traps = "traps",
    triceps = "triceps",
    shoulders = "shoulders",
    back = "back",
    chest = "chest",
    lats = "lats",
    neck = "neck",
    hamstrings = "hamstrings",
    quadriceps = "quadriceps",
    glutes = "glutes",
    calves = "calves",
    forearms = "forearms",
    biceps = "biceps"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInjuryLog(muscleGroup: MuscleGroup, dateOfInjury: Time, description: string): Promise<bigint>;
    addWorkoutLog(log: WorkoutLog): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCallerWorkoutLogs(): Promise<void>;
    deleteInjuryLog(id: bigint): Promise<void>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getAllWorkoutLogsForCaller(): Promise<Array<WorkoutLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyProteinRequirementsForCaller(): Promise<UserProteinRequirements>;
    getInjuryLogsForCaller(): Promise<Array<InjuryLog>>;
    getLeanMassForCaller(): Promise<number | null>;
    getOptimalProteinRangeForCaller(): Promise<[number, number] | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    resolveInjuryLog(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Gender as _Gender, Goal as _Goal, InjuryLog as _InjuryLog, MuscleGroup as _MuscleGroup, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutLog as _WorkoutLog } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInjuryLog(arg0: MuscleGroup, arg1: Time, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInjuryLog(to_candid_MuscleGroup_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInjuryLog(to_candid_MuscleGroup_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async addWorkoutLog(arg0: WorkoutLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkoutLog(to_candid_WorkoutLog_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkoutLog(to_candid_WorkoutLog_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCallerWorkoutLogs(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallerWorkoutLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallerWorkoutLogs();
            return result;
        }
    }
    async deleteInjuryLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInjuryLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInjuryLog(arg0);
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkoutLogsForCaller(): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkoutLogsForCaller();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkoutLogsForCaller();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyProteinRequirementsForCaller(): Promise<UserProteinRequirements> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyProteinRequirementsForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyProteinRequirementsForCaller();
            return result;
        }
    }
    async getInjuryLogsForCaller(): Promise<Array<InjuryLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInjuryLogsForCaller();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInjuryLogsForCaller();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeanMassForCaller(): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeanMassForCaller();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeanMassForCaller();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOptimalProteinRangeForCaller(): Promise<[number, number] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOptimalProteinRangeForCaller();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOptimalProteinRangeForCaller();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resolveInjuryLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveInjuryLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveInjuryLog(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Gender_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_InjuryLog_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InjuryLog): InjuryLog {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_MuscleGroup_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroup): MuscleGroup {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutLog_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutLog): WorkoutLog {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[number, number]]): [number, number] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isBodyWeight: boolean;
    reps: bigint;
    sets: bigint;
    weightKg: number;
    timestamp: _Time;
    exerciseName: string;
    muscleGroup: _MuscleGroup;
}): {
    isBodyWeight: boolean;
    reps: bigint;
    sets: bigint;
    weightKg: number;
    timestamp: Time;
    exerciseName: string;
    muscleGroup: MuscleGroup;
} {
    return {
        isBodyWeight: value.isBodyWeight,
        reps: value.reps,
        sets: value.sets,
        weightKg: value.weightKg,
        timestamp: value.timestamp,
        exerciseName: value.exerciseName,
        muscleGroup: from_candid_MuscleGroup_n17(_uploadFile, _downloadFile, value.muscleGroup)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    description: string;
    isResolved: boolean;
    muscleGroup: _MuscleGroup;
    dateOfInjury: _Time;
}): {
    id: bigint;
    description: string;
    isResolved: boolean;
    muscleGroup: MuscleGroup;
    dateOfInjury: Time;
} {
    return {
        id: value.id,
        description: value.description,
        isResolved: value.isResolved,
        muscleGroup: from_candid_MuscleGroup_n17(_uploadFile, _downloadFile, value.muscleGroup),
        dateOfInjury: value.dateOfInjury
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bodyFat: number;
    heightCm: number;
    goal: _Goal;
    weightKg: number;
    gender: _Gender;
}): {
    age: bigint;
    bodyFat: number;
    heightCm: number;
    goal: Goal;
    weightKg: number;
    gender: Gender;
} {
    return {
        age: value.age,
        bodyFat: value.bodyFat,
        heightCm: value.heightCm,
        goal: from_candid_Goal_n10(_uploadFile, _downloadFile, value.goal),
        weightKg: value.weightKg,
        gender: from_candid_Gender_n12(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recomposition: null;
} | {
    buildMaxMuscle: null;
} | {
    buildLeanMuscle: null;
}): Goal {
    return "recomposition" in value ? Goal.recomposition : "buildMaxMuscle" in value ? Goal.buildMaxMuscle : "buildLeanMuscle" in value ? Goal.buildLeanMuscle : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    abs: null;
} | {
    traps: null;
} | {
    triceps: null;
} | {
    shoulders: null;
} | {
    back: null;
} | {
    chest: null;
} | {
    lats: null;
} | {
    neck: null;
} | {
    hamstrings: null;
} | {
    quadriceps: null;
} | {
    glutes: null;
} | {
    calves: null;
} | {
    forearms: null;
} | {
    biceps: null;
}): MuscleGroup {
    return "abs" in value ? MuscleGroup.abs : "traps" in value ? MuscleGroup.traps : "triceps" in value ? MuscleGroup.triceps : "shoulders" in value ? MuscleGroup.shoulders : "back" in value ? MuscleGroup.back : "chest" in value ? MuscleGroup.chest : "lats" in value ? MuscleGroup.lats : "neck" in value ? MuscleGroup.neck : "hamstrings" in value ? MuscleGroup.hamstrings : "quadriceps" in value ? MuscleGroup.quadriceps : "glutes" in value ? MuscleGroup.glutes : "calves" in value ? MuscleGroup.calves : "forearms" in value ? MuscleGroup.forearms : "biceps" in value ? MuscleGroup.biceps : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutLog>): Array<WorkoutLog> {
    return value.map((x)=>from_candid_WorkoutLog_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InjuryLog>): Array<InjuryLog> {
    return value.map((x)=>from_candid_InjuryLog_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_MuscleGroup_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): _MuscleGroup {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutLog_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutLog): _WorkoutLog {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bodyFat: number;
    heightCm: number;
    goal: Goal;
    weightKg: number;
    gender: Gender;
}): {
    age: bigint;
    bodyFat: number;
    heightCm: number;
    goal: _Goal;
    weightKg: number;
    gender: _Gender;
} {
    return {
        age: value.age,
        bodyFat: value.bodyFat,
        heightCm: value.heightCm,
        goal: to_candid_Goal_n29(_uploadFile, _downloadFile, value.goal),
        weightKg: value.weightKg,
        gender: to_candid_Gender_n31(_uploadFile, _downloadFile, value.gender)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isBodyWeight: boolean;
    reps: bigint;
    sets: bigint;
    weightKg: number;
    timestamp: Time;
    exerciseName: string;
    muscleGroup: MuscleGroup;
}): {
    isBodyWeight: boolean;
    reps: bigint;
    sets: bigint;
    weightKg: number;
    timestamp: _Time;
    exerciseName: string;
    muscleGroup: _MuscleGroup;
} {
    return {
        isBodyWeight: value.isBodyWeight,
        reps: value.reps,
        sets: value.sets,
        weightKg: value.weightKg,
        timestamp: value.timestamp,
        exerciseName: value.exerciseName,
        muscleGroup: to_candid_MuscleGroup_n1(_uploadFile, _downloadFile, value.muscleGroup)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): {
    abs: null;
} | {
    traps: null;
} | {
    triceps: null;
} | {
    shoulders: null;
} | {
    back: null;
} | {
    chest: null;
} | {
    lats: null;
} | {
    neck: null;
} | {
    hamstrings: null;
} | {
    quadriceps: null;
} | {
    glutes: null;
} | {
    calves: null;
} | {
    forearms: null;
} | {
    biceps: null;
} {
    return value == MuscleGroup.abs ? {
        abs: null
    } : value == MuscleGroup.traps ? {
        traps: null
    } : value == MuscleGroup.triceps ? {
        triceps: null
    } : value == MuscleGroup.shoulders ? {
        shoulders: null
    } : value == MuscleGroup.back ? {
        back: null
    } : value == MuscleGroup.chest ? {
        chest: null
    } : value == MuscleGroup.lats ? {
        lats: null
    } : value == MuscleGroup.neck ? {
        neck: null
    } : value == MuscleGroup.hamstrings ? {
        hamstrings: null
    } : value == MuscleGroup.quadriceps ? {
        quadriceps: null
    } : value == MuscleGroup.glutes ? {
        glutes: null
    } : value == MuscleGroup.calves ? {
        calves: null
    } : value == MuscleGroup.forearms ? {
        forearms: null
    } : value == MuscleGroup.biceps ? {
        biceps: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    recomposition: null;
} | {
    buildMaxMuscle: null;
} | {
    buildLeanMuscle: null;
} {
    return value == Goal.recomposition ? {
        recomposition: null
    } : value == Goal.buildMaxMuscle ? {
        buildMaxMuscle: null
    } : value == Goal.buildLeanMuscle ? {
        buildLeanMuscle: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
